### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by 235002** [fluent-plugins-nursery/fluent-plugin-pgjson#29]

**Comment by ButeForce** [comment]
I have the same error when I try to install it as part of helm chart on kubernetes , is it still available and supported ?

**Comment by ttsrg** [comment]
> I'm trying to install plugin and getting this occurrence. Is there any way to fix it?
> 
> ```
> root@ :/etc/td-agent# /usr/sbin/td-agent-gem install fluent-plugin-pgjson
> Building native extensions.  This could take a while...
> ERROR:  Error installing fluent-plugin-pgjson:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/pg-1.2.2/ext
> /opt/td-agent/embedded/bin/ruby -r ./siteconf20200318-15492-9vd899.rb extconf.rb
> checking for pg_config... no
> No pg_config... trying anyway. If building fails, please try again with
>  --with-pg-config=/path/to/pg_config
> checking for libpq-fe.h... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
> 	--with-opt-dir
> 	--with-opt-include
> 	--without-opt-include=${opt-dir}/include
> 	--with-opt-lib
> 	--without-opt-lib=${opt-dir}/lib
> 	--with-make-prog
> 	--without-make-prog
> 	--srcdir=.
> 	--curdir
> 	--ruby=/opt/td-agent/embedded/bin/$(RUBY_BASE_NAME)
> 	--with-pg
> 	--without-pg
> 	--enable-windows-cross
> 	--disable-windows-cross
> 	--with-pg-config
> 	--without-pg-config
> 	--with-pg_config
> 	--without-pg_config
> 	--with-pg-dir
> 	--without-pg-dir
> 	--with-pg-include
> 	--without-pg-include=${pg-dir}/include
> 	--with-pg-lib
> 	--without-pg-lib=${pg-dir}/lib
> /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:468:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
> 	from /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:599:in `try_cpp'
> 	from /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:1160:in `block in find_header'
> 	from /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:957:in `block in checking_for'
> 	from /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
> 	from /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'
> 	from /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
> 	from /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'
> 	from /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
> 	from /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:956:in `checking_for'
> 	from /opt/td-agent/embedded/lib/ruby/2.4.0/mkmf.rb:1159:in `find_header'
> 	from extconf.rb:54:in `<main>'
> 
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
>   /opt/td-agent/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/pg-1.2.2/mkmf.log
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/pg-1.2.2 for inspection.
> Results logged to /opt/td-agent/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/pg-1.2.2/gem_make.out
> ```

apt install make libffi-dev gcc (possible ruby-dev) helps you.

**Comment by ttsrg** [comment]
or try install td-agent v4 instead of the more oldest

**Comment by ButeForce** [comment]
Hi I solved this issue by uninstalling the tzinfo-2.0.0 and depending on the installed version which comes with the connector. "gem uninstall tzinfo -v 2.0.2 " in the Dockerfile

**Comment by cosmo0920** [comment]
This error should be occurred from lack of building toolchain such as gcc and make.
You must install C language development tools first.
This plugin depends on pg gem which contains C extensions.
